meili.endpoint=http://localhost:7070
mp.jwt.verify.publickey.location=src/main/resources/publicKey.pem
mp.jwt.verify.issuer=https://example.com/issuer
mp.jwt.token.header=Cookie
mp.jwt.token.cookie=jwt
quarkus.log.category."io.smallrye.jwt".level=DEBUG
quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.quarkus.smallrye.jwt".level=DEBUG
quarkus.datasource.devservices.port=5432
quarkus.rest-client."org.acme.rest.CardReferenceService".url=https://api.riftcodex.com/cards
quarkus.native.resources.includes=src/main/resources/publicKey.pem
smallrye.jwt.sign.key.location=src/main/resources/privateKey.pem
smallrye.jwt.always-check-authorization=true
%prod.quarkus.datasource.db-kind = postgresql
%prod.quarkus.datasource.username = leopold
%prod.quarkus.datasource.password = bloom
%prod.quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/mydatabase
